### ISSUE TITLE
Recursive makefile ?

### ISSUE THREAD

**Issue by RMPR** [wilcoln/be-enseeiht-openmp#1]

**Comment by wilcoln** [comment]
Gaaar... c'est les sources du prof, moi rien là dedans

**Comment by wilcoln** [comment]
Mais en fait ce qui se passe c'est que chaque "sous projet" a un Makefile, qui lui a une tête normale.
Le Makefile du projet global ne sert qu'à build les sous projet en appelant, pour chacun, son Makefile propre.
